### ISSUE TITLE
OpenLLM supports fine-tuning now

### ISSUE THREAD

**Issue by Jason-cs18** [AIoT-MLSys-Lab/Efficient-LLMs-Survey#12]
Hi team, thanks for your awesome work. 

I discovered that OpenLLM has been integrated with HuggingFace PEFT and supports LLM fine-tuning layers. You can see the documentation here: https://github.com/bentoml/OpenLLM#%EF%B8%8F-serving-fine-tuning-layers

**Comment by SUSTechBruce** [comment]
Thank you for your suggestion, we will cover this latest content in the new version~
