### ISSUE TITLE
Quantization equation error

### ISSUE THREAD

**Issue by Honei** [AIoT-MLSys-Lab/Efficient-LLMs-Survey#24]
I find some error in the first quantization equation, I cannot find the variable $H^{H}$

![image](https://github.com/AIoT-MLSys-Lab/Efficient-LLMs-Survey/assets/11361692/705a8d88-ad32-47a7-856a-51fd1d8103c8)

**Comment by SUSTechBruce** [comment]
Thanks a lot for pointing this out. It is indeed a typo. H^{H} should be X^{H}. We will fix this typo in the next version of the survey.
