### ISSUE TITLE
A NeurIPS paper on efficient architecture

### ISSUE THREAD

**Issue by renll** [AIoT-MLSys-Lab/Efficient-LLMs-Survey#3]
Thanks for the great survey! Could you please include a discussion of this [work](https://arxiv.org/abs/2306.11197) from Microsoft and UIUC? It proposes a general modular activation mechanism, SMA, that unifies previous works on MoE, adaptive computation, dynamic routing and sparse attention, and further applies SMA to develop a novel architecture, SeqBoat, to achieve SoTA quality-efficiency trade-off on Long Range Arena.

**Comment by SUSTechBruce** [comment]
Thanks for the suggestion and congrats on your NeurIPS paper!
We've added it to the github paperlist and will update it to survey in next version~
