### ISSUE TITLE
Suggest including an efficient LLM inference work

### ISSUE THREAD

**Issue by ZexinLi0w0** [AIoT-MLSys-Lab/Efficient-LLMs-Survey#5]
Thanks for the great survey! I have a kind suggestion of including a discussion of this state-of-the-art work [Medusa](https://sites.google.com/view/medusa-llm) in the efficient LLM inference part.

Code repo: https://github.com/FasterDecoding/Medusa
Blog website: https://sites.google.com/view/medusa-llm
"Medusa: Simple Framework for Accelerating LLM Generation with Multiple Decoding Heads"

**Comment by SUSTechBruce** [comment]
Thanks for the suggestion !
We've added it to the github paperlist and will update it to survey in next version~
